server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${API_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: PROTOCOL_TLSv1_2

authentication:
  username: ${API_USER}
  password: ${API_PASSWD}
