swagger: "2.0"

info:
  title: "Tweet API"
  description: "This provides an API for creating a message (post), reading a message (get), editing a message (put), delete a message (delete)."
  version: "1.0"

host: localhost

tags:
- name: "tweets"

schemes:
  - "https"

consumes:
  - application/json
produces:
  - application/json

paths:

  /tweets:
  
    get:
      tags:
      - tweets
      description: "search for a user's tweets"
      produces:
      - application/json

      parameters:
      - in: "query"
        name: userName
        required: false
        type: string

      - in: "query"
        name: tweetId
        required: false
        type: integer

      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/tweetsData"
        400:
          description: The specified user ID is invalid
          schema:
            $ref: "#/definitions/Error"
        404:
          description: page not found
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Invalid input
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

    post:
      tags:
      - tweets
      description: "post a new tweet"
      produces:
      - application/json

      parameters:
        - name: body
          in: body
          description: "tweet will be created and posted"
          required: true
          schema:
            $ref: "#/definitions/tweetsData"

      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/tweetsData"
        204:
          description: No content
          schema:
            $ref: "#/definitions/Error"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        404:
          description: page not found
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Invalid input
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /tweets/{tweetId}:

    get:
      tags:
        - tweets
      description: "Find a tweet by tweet ID"
      produces:
      - application/json
      parameters:
        - name: tweetId
          in: path
          required: true
          type: integer

      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/tweetsData"
        204:
          description: No content
          schema:
            $ref: "#/definitions/Error"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        404:
          description: page not found
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Invalid input
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

    put:
      tags:
      - tweets
      description: "update a tweet"
      produces:
      - application/json

      parameters:
        - name: tweetId
          in: path
          description: "update the tweet"
          required: true
          type: integer

        - name: body
          in: body
          description: "tweet content to be updated"
          required: true
          schema:
            $ref: "#/definitions/tweetsData"

      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/tweetsData"
        204:
          description: No content
          schema:
            $ref: "#/definitions/Error"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        404:
          description: page not found
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Invalid input
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

    delete:
      tags:
        - tweets
      description: "Delete a tweet"
      produces:
      - application/json

      parameters:
        - name: tweetId
          in: path
          description: "delete the tweet"
          required: true
          type: integer

      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/tweetsData"
        204:
          description: No content
          schema:
            $ref: "#/definitions/Error"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/Error"
        404:
          description: page not found
          schema:
            $ref: "#/definitions/Error"
        405:
          description: Invalid input
          schema:
            $ref: "#/definitions/Error"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"


definitions:
  tweetsData:
    properties:
      userName:
        type: string
      tweetId:
        type: integer
      tweet:
        type: string

  Error:
      properties:
        error message:
          type: "string"
        error code:
          type: "integer"
