-- USER_DATA table for holding the user information (USER_ID, USERNAME, USER_FULL_NAME)
CREATE TABLE USER_DATA(
    USER_ID NUMBER NOT NULL,
    USERNAME VARCHAR2(255 char) NOT NULL,
    USER_FULL_NAME VARCHAR2(255 char),
    PRIMARY KEY (USER_ID)
);

COMMENT ON TABLE USER_DATA IS 'Contains the data for the user, e.g (USER ID, USERNAME, USER FULL NAME)';
COMMENT ON COLUMN USER_DATA.USER_ID IS 'ID of users';
COMMENT ON COLUMN USER_DATA.USERNAME IS 'Username name';
COMMENT ON COLUMN USER_DATA.USER_FULL_NAME IS 'User full name';

-- sequence counter for the unique user ID, starts from 1 and increment by 1
CREATE SEQUENCE seq_USER_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

INSERT INTO USER_DATA (USER_ID, USERNAME, USER_FULL_NAME) VALUES (seq_USER_ID.nextval, Mohammed, "Mohammed Alawami");
INSERT INTO USER_DATA (USER_ID, USERNAME, USER_FULL_NAME) VALUES (seq_USER_ID.nextval, IanW, "Ian Wilson");
INSERT INTO USER_DATA (USER_ID, USERNAME, USER_FULL_NAME) VALUES (seq_USER_ID.nextval, IanB, "Ian Brown");
INSERT INTO USER_DATA (USER_ID, USERNAME, USER_FULL_NAME) VALUES (seq_USER_ID.nextval, Liang, "Tso-Liang Wu");

-- TWEET_DATA table holds the tweet information, (USER_ID, TWEET_ID, TWEET_MSG, TITLE, MOOD, TIME_AND_DATE)
CREATE TABLE TWEET_DATA(
    USER_ID NUMBER NOT NULL,
    TWEET_ID VARCHAR2(255 char)  NOT NULL,
    TWEET_MSG VARCHAR2(255 char),
    TITLE VARCHAR2(255 char),
    MOOD VARCHAR2(255 char),
    TIME_AND_DATE VARCHAR2(255 char),
    FOREIGN KEY (USER_ID) REFERENCES USER_DATA(USER_ID),
    PRIMARY KEY (TWEET_ID)
);

COMMENT ON TABLE TWEET_DATA IS 'Contains inforamtion and content of the tweet';
COMMENT ON COLUMN TWEET_DATA.USER_ID IS 'ID of the owner of the tweet';
COMMENT ON COLUMN TWEET_DATA.TWEET_ID IS 'ID of the tweet';
COMMENT ON COLUMN TWEET_DATA.TWEET_MSG IS 'Content of tweet message';
COMMENT ON COLUMN TWEET_DATA.TITLE IS 'Title of the tweet message';
COMMENT ON COLUMN TWEET_DATA.MOOD IS 'The mood of the user while typeing the tweet message';
COMMENT ON COLUMN TWEET_DATA.Time_AND_DATE IS 'The time and date of the tweet message';

CREATE SEQUENCE seq_TWEET_ID
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

INSERT INTO TWEET_DATA (USER_ID, TWEET_ID, TWEET_MSG, TITLE, MOOD, TIME_AND_DATE) VALUES (1, seq_TWEET_ID.nextval, "Hello World!", "First Tweet", "Happy", "2018-10-22T11:28:22+00:00");
